[package]
name = "keyspace-programs-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
k256 = "0.13.3"
serde = { version = "1.0.210", features = ["derive"] }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
